version: '2.1'
services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: SqlServer
        environment:
            MSSQL_SA_PASSWORD: hahn2023#
            SA_PASSWORD: hahn2023#
            ACCEPT_EULA: Y
            MSSQL_PID: Express
        ports:
            - 1433:1433

    mssqltools:
        image: mcr.microsoft.com/mssql-tools
        container_name: SqlTools
        depends_on:
            - sqlserver
        volumes:
            - ./scripts/setup.sql:/tmp/setup.sql
            - ./scripts/entrypoint.sh:/tmp/entrypoint.sh
        command: /bin/bash ./tmp/entrypoint.sh

    api:
        image: rafaelarduini/hahn-api:v1
        container_name: Api
        restart: always
        build:
            context: back-end
            dockerfile: ./HahnSoftwareentwicklung.Api/Dockerfile
        ports:
            - 80:80
        deploy:
            labels:
            - "com.microsoft.created-by=visual-studio"
            - "com.microsoft.visual-studio.project-name=HahnSoftwareentwicklung.Api"
        depends_on:
            - mssqltools

    web:
        image: rafaelarduini/hahn-front-end:v1
        container_name: Web
        build: ./front-end
        environment:
            NODE_ENV: production
        ports:
            - 4200:4200
        depends_on:
            - api
